name: Vue project Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  deploying_vue_project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false
      - name: building
        # 执行shell命令
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: master
          folder: dist
